### PR TITLE
Load pre-trained word embeddings for input and output

### PR DESCRIPTION
**Pull request by evanmiltenburg**
Here's the next update to the code. The embeddings are now initialisable for both input and output, using separate keywords.

### CODE REVIEW

**Comment by elliottd** [comment]
Thanks! Do these new options introduce any major performance regressions?

**Comment by evanmiltenburg** [comment]
I'm training a plain model at the moment. Will update with the performance later.

**Comment by evanmiltenburg** [comment]
Val: 

BLEU = 16.57, 58.1/25.7/10.6/4.8 (BP=1.000, ratio=1.011, hyp_len=10515, ref_len=10404)
INFO:__main__:Meteor = 15.85 | BLEU = 16.57 | TER = 65.50

Test:

BLEU = 15.65, 57.5/24.5/10.2/4.2 (BP=0.998, ratio=0.998, hyp_len=10125, ref_len=10148)
INFO:__main__:Meteor = 15.57 | BLEU = 15.65 | TER = 65.95

Does look like some regression is taking place. (about 1 BLEU and <0.5 Meteor).

**Comment by evanmiltenburg** [comment]
Fun fact: Meteor and BLEU diverge more if you initialize both input and output embeddings. Here's the results for Test with both initialized with the GoogleNews vectors:

BLEU = 14.78, 51.9/22.5/9.7/4.2 (BP=1.000, ratio=1.071, hyp_len=13920, ref_len=12995)
INFO:__main__:Meteor = 16.83 | BLEU = 14.78 | TER = 86.38

Competitive Meteor, but BLEU suffers!

**Comment by elliottd** [comment]
Accepting the pull request because there is no guarantee that initialising the model from pre-trained embeddings should improve performance. And the pull request makes it possible to still use the default option.

**Pull request merged**
